USE DvdLibrary;
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES
	WHERE ROUTINE_NAME = 'DvdDbReset')
		DROP PROCEDURE DvdDbReset
GO

CREATE PROCEDURE DvdDbReset AS
BEGIN
	DELETE FROM Dvds;
	DELETE FROM Directors;
	DELETE FROM Ratings;

	DBCC CHECKIDENT ('dvds', RESEED, 1)
	DBCC CHECKIDENT ('directors', RESEED, 1)

	SET IDENTITY_INSERT Ratings ON;
	INSERT INTO Ratings (RatingId, RatingName)
	VALUES (1, 'G'),
	(2, 'PG'),
	(3, 'PG-13'),
	(4, 'R')
	SET IDENTITY_INSERT Ratings OFF;
END